### ISSUE TITLE
Implement a ChangeKey() widget

### ISSUE THREAD

**Issue by gjwgit** [anusii/solidpod#102]
## User Story

As a user of solidpod in my app I want to allow the user to change the key. I might have decided it is too simple, or that I think it might have been compromised and needs to be changed. 

## Why

So that a user app can provide their users with the ability to update the key used for encryption.

## Closing Criteria

- [x] Keypod has a button that brings up this widget and the key can be changed by the user
- [x] There should be a CANCEL button in case I change my mind

## Backend Task

This task focuses on the front end, the corresponding backend task is #111

## Details

The Gurriny Indi (Patient) app has now implemented this thanks to @anushkavidanage. 

![image](https://github.com/anusii/solidpod/assets/1681429/6cce83f2-e7b4-47fc-be70-6ddc380e5b20)

The Change Encryption Key and below to the WebID are to be provided as a single Widget that I simply place in my app where I want it.

**Comment by cdawei** [comment]
There is a backend task and a front end task for this issue, I suggest we make them explicit in the task list.

**Comment by junhaow1** [comment]
<img width="861" alt="image" src="https://github.com/anusii/solidpod/assets/37771259/ec061b3d-f214-46ca-8a7f-4ac5c8938554">

**Comment by junhaow1** [comment]
working branch : https://github.com/anusii/solidpod/tree/kev/102

**Comment by junhaow1** [comment]
https://github.com/anusii/solidpod/pull/113 PR created

**Comment by junhaow1** [comment]
demo:

- [ ] back button works 

https://github.com/anusii/solidpod/assets/37771259/82cbd980-85eb-4526-a62e-88909daf045e

**Comment by gjwgit** [comment]
Can we please not simply extend the widget to the whole page width - it looks rather ugly. Perhaps experiment with best layout.

**Comment by junhaow1** [comment]
> Can we please not simply extend the widget to the whole page width - it looks rather ugly. Perhaps experiment with best layout.

agree, on it

**Comment by gjwgit** [comment]
I wonder if the ChangeKey() would work better as a ChangeKeyPopup(): So in my app I tap the Change Key button and a popup is presented. The layout will be a no brainer then and more in keeping with the transient nature of changing the key.

**Comment by junhaow1** [comment]
demo: 

https://github.com/anusii/solidpod/assets/37771259/12971997-8c74-4b04-a402-91717e59734c


PR created 
https://github.com/anusii/solidpod/pull/113

**Comment by junhaow1** [comment]
![Image](https://github.com/anusii/solidpod/assets/37771259/acc953c4-a8ee-4276-b931-226457c3159e)

**Comment by gjwgit** [comment]
I think the widget should be a popup, not the button? My app will decide if a button or an icon, etc.

**Comment by junhaow1** [comment]
> I think the widget should be a popup, not the button? My app will decide if a button or an icon, etc.

ok on it

**Comment by junhaow1** [comment]
https://github.com/anusii/solidpod/issues/111 backend part

**Comment by junhaow1** [comment]
use changeKeyPopup in KeyPod
<img width="589" alt="image" src="https://github.com/anusii/solidpod/assets/37771259/78c5775c-8471-46f0-8ecc-a7712b1a118f">

**Comment by cdawei** [comment]
Use "security key" instead of "encryption key".

**Comment by junhaow1** [comment]
renamed 



![Image](https://github.com/anusii/solidpod/assets/37771259/08a86f9e-e9ff-4b26-9751-c52a3bf550e7)



> Use "security key" instead of "encryption key".

**Comment by junhaow1** [comment]
merged. can be closed
