### ISSUE TITLE
Initialise Pod needs to have "Show Password" buttons

### ISSUE THREAD

**Issue by gjwgit** [anusii/solidpod#104]
![Image](https://github.com/anusii/solidpod/assets/1681429/76091c12-0e4a-4367-b89d-57afa70e3cc0)

**Comment by junhaow1** [comment]
<img width="747" alt="image" src="https://github.com/anusii/solidpod/assets/37771259/b9dfd55a-61d6-418c-9e35-f34105beb859">
<img width="751" alt="image" src="https://github.com/anusii/solidpod/assets/37771259/6f0fa6c4-d0ec-4552-a29a-1f5a586cb165">

**Comment by junhaow1** [comment]
PR created https://github.com/anusii/solidpod/pull/105

- [ ] make prep
