### ISSUE TITLE
SOLID POD: Login animation does not disappear

### ISSUE THREAD

**Issue by cdawei** [anusii/solidpod#122]
![Image](https://github.com/anusii/solidpod/assets/13044715/045af755-bd46-42c3-9d74-3d16e697ca4d)
The logging in animation does not disappear automatically after successfully logging in, need to manually click the "Cancel" button to dismiss it.

To reproduce:
1. Start keypod and click "Login"
1. Click "Logout" at the top left corner of the test page
1. Click "Login" to log in again

**Comment by cdawei** [comment]
> I am not able to reproduce in current dev (keypod/solidpod).
> 
> The top left logout is gone but now tap the Logout From Remote Solid Server.

I can still reproduce the issue using the current dev (keypod/solidpod). Did you login again right after logging out (i.e. the 3rd step in the issue description)?

**Comment by zheyxu** [comment]
Keeps failing on https://github.com/anusii/solidpod/blob/52a3c476444a5d42827b4a0fb0270cc463a29bcd/lib/src/solid/utils/misc.dart#L203

**Comment by zheyxu** [comment]
Made pr https://github.com/anusii/solidpod/pull/136 to fix the issue
