### ISSUE TITLE
SOLID POD: Click the EYE in the Secret Key entry popup and the key I've entered disappears?

### ISSUE THREAD

**Issue by cdawei** [anusii/solidpod#124]

**Comment by junhaow1** [comment]
need some clarification 

![Image](https://github.com/anusii/solidpod/assets/37771259/0198d809-88fa-49a6-b682-862613356c71)



![Image](https://github.com/anusii/solidpod/assets/37771259/40fb33f3-adf1-4c2d-a8e0-5661ad6b0784)

**Comment by cdawei** [comment]
It is this screen, and the widget is located in [`solidpod/lib/src/widgets/password_input_screen.dart`](https://github.com/anusii/solidpod/blob/dev/lib/src/widgets/password_input_screen.dart)
![Image](https://github.com/anusii/solidpod/assets/13044715/6c576f0a-d28e-4c66-9b53-ba61fe1ac7f5)

To reproduce the problem:
1. Start keypod and click "Continue"
2. Click "Delete master password" and "OK"
3. Click "Key value demo"
4. Type something in the input field and click the "Eye" icon

**Comment by junhaow1** [comment]
fixed in https://github.com/anusii/solidpod/issues/151

**Comment by cdawei** [comment]
Superceded by #151
