### ISSUE TITLE
SOLID POD: Manage permissions of resources in PODs

### ISSUE THREAD

**Issue by cdawei** [anusii/solidpod#128]
Implement permission management of resources in PODs. Code in https://github.com/anusii/gurriny is likely useful for this. 

Many sub-tickets/issues will be created for this placeholder issue.

**Comment by anushkavidanage** [comment]
Sub tasks

- [ ] Create a UI for grant permissions for both encrypted and unencrypted data
- [ ] Create a UI for viewing permissions
- [ ] Create a UI for editing/revoking permissions
- [ ] Backend for extracting permission details for a file
- [ ] Backend for granting permissions for a file
- [ ] Backend for revoking permissions for a file

**Comment by anushkavidanage** [comment]
Shall we close this issue since we have now created sub tasks for the above

**Comment by cdawei** [comment]
Sure, thanks Anushka.
