### ISSUE TITLE
SOLID POD: Secure Key request when entered and press ENTER it should be same as OK

### ISSUE THREAD

**Issue by gjwgit** [anusii/solidpod#129]
## User Story

After I have typed the key here, as a user I am inclined to press ENTER. This should be the same a tapping the OK button.

![Image](https://github.com/anusii/solidpod/assets/1681429/72852174-5f0a-46bd-b51e-6c35a814018d)

**Comment by cdawei** [comment]
Implemented in pull request https://github.com/anusii/solidpod/pull/164

To test, go to the keypod demo page and
1. Click "Forget Security Key"
2. Turn on the "Encrypt Data" switch
3. Click "Key Value Table Demo"
4. Add a key-value pair and click "Submit"
5. In the security key input widget, type your security key and press the enter key.
![delete_file](https://github.com/anusii/solidpod/assets/13044715/bd7a1f43-61bc-4590-a907-e826c924266a)

Known issue:
- If you move the input focus off the text input after typing your security key, then press the enter key seems to do nothing (haven't been able to find a fix for this so far).

**Comment by gjwgit** [comment]
Tested and works as expected
