### ISSUE TITLE
SOLID POD: Display the version on the login screen

### ISSUE THREAD

**Issue by gjwgit** [anusii/solidpod#135]
## User Story

As a user I like to know what version of the app I am running and the login screen has space for it with *Version* text there, but no version number is shown.

This task is to retrieve the app's version number and display it on the login screen.

![Image](https://github.com/anusii/solidpod/assets/1681429/6c9943b3-b75d-464d-8a43-072c324907e0)

**Comment by junhaow1** [comment]
<img width="859" alt="image" src="https://github.com/anusii/solidpod/assets/37771259/e438da71-6137-4d32-89e1-51a6bb8b7068">

**Comment by junhaow1** [comment]
<img width="864" alt="image" src="https://github.com/anusii/solidpod/assets/37771259/09560b10-1215-42bb-bf1f-4a73fdd7b3cf">
PR https://github.com/anusii/solidpod/pull/139 created 
thanks @gjwgit  for reminding PackageInfo
