### ISSUE TITLE
SOLID POD: API for revoking permissions from a file

### ISSUE THREAD

**Issue by anushkavidanage** [anusii/solidpod#145]

**Comment by anushkavidanage** [comment]
![remove-perm](https://github.com/anusii/solidpod/assets/81279146/4fe1d17a-2b3a-412e-86a7-36112cd5c457)

**Comment by gjwgit** [comment]
In the screenshot which permission is being removed from who?

**Comment by anushkavidanage** [comment]
Fixed the UI side

![Image](https://github.com/anusii/solidpod/assets/81279146/78cd0cb7-286a-4438-a503-965b834eb389)
