### ISSUE TITLE
KEYPOD: SAVE remains active after deleting a newly created key value pair

### ISSUE THREAD

**Issue by anushkavidanage** [anusii/solidpod#147]

**Comment by gjwgit** [comment]
The SAVE button logic could be improved to notice when an inserted row is deleted and so we are back to the saved version of the data. If this is tricky then let's retain the current simpler logic for the template.



![Image](https://github.com/anusii/solidpod/assets/1681429/4ff67b4c-4584-492a-b274-9da08de33257)

@junhaow1 to assess on complexity and advise.

**Comment by junhaow1** [comment]
> The SAVE button logic could be improved to notice when an inserted row is deleted and so we are back to the saved version of the data. If this is tricky then let's retain the current simpler logic for the template.

on it :)

**Comment by zheyxu** [comment]
Find the Save does not support empty key value pair.
`_AssertionError ('package:keypod/utils/rdf.dart': Failed assertion: line 46 pos 10: 'keyValuePairs.isNotEmpty': is not true.)`

**Comment by zheyxu** [comment]
And occasionally the data table fails to add new record.
