### ISSUE TITLE
SOLIDPOD: Initialise POD - cannot see the list of resources that are being created

### ISSUE THREAD

**Issue by anushkavidanage** [anusii/solidpod#150]

**Comment by gjwgit** [comment]
Oh dear - yes. What happened to the list???

![image](https://github.com/anusii/solidpod/assets/1681429/da1f3051-3294-4b27-a8d9-2ad493139682)

**Comment by cdawei** [comment]
I got this issue as well while working on #117, it is due to the additional `/` in `resourceUrl` in [this line](https://github.com/anusii/solidpod/blob/7db74848115ae10c7dfd8833aa6a0edd0cd25ec0/lib/src/solid/api/rest_api.dart#L126). It should be fixed in https://github.com/anusii/solidpod/pull/153

**Comment by junhaow1** [comment]
tested,  fixed by Dawei :) 

![Image](https://github.com/anusii/solidpod/assets/37771259/0a1f9271-cb7d-47a2-b866-a6d55ed58336)
