### ISSUE TITLE
KEYPOD: The textfield for entering security key reloads when I press the `eye` icon

### ISSUE THREAD

**Issue by anushkavidanage** [anusii/solidpod#151]

**Comment by gjwgit** [comment]
Not able to replicate this - what are the steps required to do so?

**Comment by cdawei** [comment]
Is this the same issue as in https://github.com/anusii/solidpod/issues/124 ?

**Comment by junhaow1** [comment]
how to replicate: 
https://github.com/anusii/solidpod/assets/37771259/9db6840b-c552-4554-a2b3-b915e09a37f3


after the fix: 

https://github.com/anusii/solidpod/assets/37771259/1b9fc43a-e7a5-4dd3-97e5-9c94f8c4bfc1



https://github.com/anusii/solidpod/pull/154 PR created
