### ISSUE TITLE
KEYPOD: Visibility of `ok` and `cancel` buttons are low in the security key input widget

### ISSUE THREAD

**Issue by anushkavidanage** [anusii/solidpod#152]

**Comment by gjwgit** [comment]
Where exactly are these?

**Comment by cdawei** [comment]
It is likely this widget
![Image](https://github.com/anusii/solidpod/assets/13044715/797e0b2e-9505-45fc-a81b-82c39607a578)

To reproduce:
1. Start `keypod` and click `Continue`
2. Click `Testing` then click `Forge Local Security Key`
3. Restart `keypod` and click `Continue`
4. Click `+` to add a new row, enter a key-value pair, and click `Save`

**Comment by junhaow1** [comment]
fixed in https://github.com/anusii/solidpod/pull/154
