### ISSUE TITLE
PERMISSION: Add `Append` in the permission list

### ISSUE THREAD

**Issue by cdawei** [anusii/solidpod#180]
Besides `Read`, `Write`, `Control` as currently implemented. We may also want consider the `Append` access mode as per the [Web ACL specification](https://solidproject.org/TR/wac#acl-mode-append).

**Comment by anushkavidanage** [comment]
![append](https://github.com/anusii/solidpod/assets/81279146/abf3f8ef-6ac3-4372-9a9e-2e80ccf84566)
