### ISSUE TITLE
PERMISSION: Add brief description for each access mode

### ISSUE THREAD

**Issue by cdawei** [anusii/solidpod#181]
A [brief description of each access mode](https://solidproject.org/TR/wac#access-modes) in the UI for granting permission would be helpful to inform the user.
The description could in the form of, for example, plain text or tooltip of the UI element for an access mode.

**Comment by anushkavidanage** [comment]
![Image](https://github.com/anusii/solidpod/assets/81279146/74ebae0f-c0ea-4a7a-9e9e-18fb0cb40b67)
