### ISSUE TITLE
PERMISSION: Use one-way hash of resource URI as unique ID of shared resource

### ISSUE THREAD

**Issue by cdawei** [anusii/solidpod#182]
The `shared-keys.ttl` uses the name of the shared file as a "unique ID" for the corresponding record (with data path, permission list and individual key, all encrypted using the recipient's RSA public key) of the shared file. This will result in the same ID for a file in a different path but with the same filename shared by the same POD.

Including the path of shared file could solve this problem, but it reveals the actual URI of the shared file (the URI can be reconstructed from the parent directory of `shared-keys.ttl` in `shared`, named with `POD_ORIGIN-POD_NAME`). This is problematic because the `shared/` folder is publicly readable and writable (for adding/deleting encryption keys when granting/revoking access permissions). 

Additionally, encrypt the URI of shared file using the recipient's public key may not work as the cipher text produced by RSA public key encryption is usually not the same (even for the same plain text) in different runs of the encryption. This is due to the randomised padding scheme used in RSA encryption (as described [here](https://stackoverflow.com/a/16329374) and [here](https://en.wikipedia.org/wiki/RSA_(cryptosystem)#Padding_schemes)). This can cause problem when granting additional permissions or revoking permissions.

Therefore, a method to create secure and unique ID for a shared resource needs to be developed.

**Comment by cdawei** [comment]
Anushka proposed to use a one way hash, for example, `sha256(RESOURCE_URI)` as the unique ID of shared resource. And include the encrypted resource URI, the list of permissions, and the encrypted individual key for one shared file.

The advantage of this approach is that we need only a single `shared-keys.ttl` file in `shared/` to store the encryption keys of all shared files (rather than one `shared-keys.ttl` for each webID that shares files as currently implemented).

**Comment by anushkavidanage** [comment]
Changes are in https://github.com/anusii/solidpod/tree/av/182_use_unique_id_for_sharing_keys

Up for a discussion
- With this change, all shared keys will be saved in a single file. Is this ok
- Anyone can read this file, but (up to some level) will not be able to extract useful information
- Anyone can delete stuff from this file. This is an issue we had previously as well. But not sure how to get around this.

**Comment by cdawei** [comment]
> Changes are in https://github.com/anusii/solidpod/tree/av/182_use_unique_id_for_sharing_keys

Thanks Anushka, this is great.

> With this change, all shared keys will be saved in a single file. Is this ok

This seems OK to me.

> Anyone can read this file, but (up to some level) will not be able to extract useful information

Public Read access seems fine.

> Anyone can delete stuff from this file. This is an issue we had previously as well. But not sure how to get around this.

Public Write access sounds problematic.

For example, someone can delete or change the encrypted individual key of the shared file which would prevent the recipient from decrypting the shared file content.

A cumbersome workaround I can think of is using two files in the `shared/` folder, both with only `Append` access for the public (the recipient of course has `Write` access), and one file stores transactions of granting permissions, the other for transactions of revoking permissions.

To make things slightly easier, the recipient could update both files (e.g. every time they start their app) to remove outdated grant/revoke permission transactions (just like how a database executes the transations in journals in data recovery).

What do you think?

**Comment by anushkavidanage** [comment]
Thanks Dawei for the suggestions. Yes, that could be a work around. However, that makes sharing a bit more complicated and recipient need to update files everytime there is a change. But this seems to be the only workaround at the moment. We could do this in one file instead of two files.

**Comment by cdawei** [comment]
Thanks Anushka. Yes, we could implement the workaround using only one file (for example, by defining permission granting and revoking predicates in our custom ontology).

I tried to capture this discussion and the tasks here https://github.com/anusii/solidpod/issues/193, please feel free to add anything I have missed.

**Comment by anushkavidanage** [comment]
Thanks Dawei. Will check that issue. Closing this as the PR has been merged.
