### ISSUE TITLE
PERMISSION: Capture permissions granted to public agents

### ISSUE THREAD

**Issue by cdawei** [anusii/solidpod#183]
The current implementation captures agents from predicate `acl:agent`. We may need to capture the permissions granted to public agent (objects of predicates `foaf:Agent` or `acl:AuthenticatedAgent`) when reading/revoking permissions, as per the [Web ACL specification](https://solidproject.org/TR/wac#access-subjects).

**Comment by anushkavidanage** [comment]
![Image](https://github.com/anusii/solidpod/assets/81279146/221de913-bb33-47d3-b954-c98b5a98b67a)

**Comment by cdawei** [comment]
Hi Anushka, could you please share the content of `pub-values.ttl.acl` used in your screenshot here? I am struggling to construct an ACL file to test pull request #192. Thanks

**Comment by anushkavidanage** [comment]
pub-values.ttl.acl content

@prefix : <#>.
@prefix acl: <http://www.w3.org/ns/auth/acl#>.
@prefix foaf: <http://xmlns.com/foaf/0.1/>.
@prefix c: <card#>.

:owner
    a acl:Authorization;
    acl:accessTo <pub-values.ttl>;
    acl:agent c:me;
    acl:mode acl:Control, acl:Read, acl:Write.

:public
    a acl:Authorization;
    acl:accessTo <pub-values.ttl>;
    acl:agentClass foaf:Agent;
    acl:mode acl:Read, acl:Write.

:group 
    a acl:Authorization;
    acl:accessTo <pub-values.ttl>;
    acl:agentGroup <user-group.ttl>;
    acl:mode acl:Read.

**Comment by cdawei** [comment]
> pub-values.ttl.acl content

Thanks Anushka for this.

It seems the [python RDFLib](https://rdflib.readthedocs.io/en/stable/index.html) cannot parse `pub-values.ttl.acl`. If I change the `@Prefix` to `@prefix` and `@Prefix acl: http://www.w3.org/ns/auth/acl#.` to `@prefix acl: <http://www.w3.org/ns/auth/acl#>.` (and similarly for `foaf`), it worked. 

This might indicate the RDF parser employed by `solidpod` may not be compatible with [python RDFLib](https://rdflib.readthedocs.io/en/stable/index.html).
