### ISSUE TITLE
SOLID POD: Read and write binary data

### ISSUE THREAD

**Issue by cdawei** [anusii/solidpod#186]
The `readPod()` and `writePod()` implicitly requires the data to read/write is a string.

However, this won't be the case when reading / writing EEG data. Solidpod needs to support the read / write of binary data (i.e. `bytes`) in addition to text data.

**Comment by cdawei** [comment]
Please follow the below steps to test.
- Start `demopod`
- Click `Upload / Download Large File` button
- Click `Browse` button to choose a local file to upload (I used the ZIP archive of [this EEG folder on next cloud](https://cloud.empwr.au/index.php/apps/files/files/9559?dir=/PODs/EEG))
- Click `Upload` button, which shows a progress bar as illustrated in the screenshot below
- To test download or delete functionality, click the `Download` or the `Delete` button, and a similar a progress bar will appear.
- After testing upload, download, and delete, expecting to see something like the screenshot below.

**Comment by gjwgit** [comment]
Tested. Works as advertised.

**Comment by cdawei** [comment]
Note that 
*A container can only be deleted if it contains no resources.*
as per https://github.com/solid/solid-spec/blob/master/api-rest.md#deleting-containers

**Comment by cdawei** [comment]
Note that this implements a workaround to issue https://github.com/anusii/solidpod/issues/214

**Comment by cdawei** [comment]
A large binary file is stored in
- a directory with chunks of the binary file and their ACL files
- and a `.ttl` file with paths of binary file chunks, for example,
```
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix sii: <https://solidproject.au/sii/> .
@prefix c: <https://pods.solidcommunity.au/dc101/exampleApp/data/.large_file.bin.chunks/> .

<https://pods.solidcommunity.au/dc101/exampleApp/data/large_file.bin>
    sii:dataSize "47354712"^^xsd:int ;
    sii:dataChunk c:0.bin, c:1.bin, c:2.bin, c:3.bin, c:4.bin, c:5.bin, c:6.bin, c:7.bin, c:8.bin, c:9.bin, c:10.bin, c:11.bin, c:12.bin, c:13.bin, c:14.bin, c:15.bin, c:16.bin, c:17.bin, c:18.bin, c:19.bin, c:20.bin, c:21.bin, c:22.bin .
```
