### ISSUE TITLE
SOLIDPOD: Implement InitialisePod()

### ISSUE THREAD

**Issue by gjwgit** [anusii/solidpod#2]
## Description

If the app's folder on the user's POD does not exist then this Widget will request approval to create it, listing the resources to be created and asking for approval. If encryption is True (as a parameter) then all of the encryption infrastructure is also created. 

This is in podnotes/initial_setup/desktop.dart for example and we can reuse a lot of that code, but be sure to document it.

Do not ask for the user's profile (name and gender) which should be in their profile already if they wanted it to be.

This is a sub task of #1

**Comment by zheyxu** [comment]
Files created = list in pic + a foder with same name in pubspec.yaml of keypods app.

![Image](https://github.com/anusii/solid/assets/79696631/6d0d8af0-70a2-4cdd-8478-6d1f43ab08e9)
![Image](https://github.com/anusii/solid/assets/79696631/b6fff428-59ab-4065-8e0d-d3e5c408c6cf)

**Comment by gjwgit** [comment]
It looks like all but one file/folder is "standard". There is then a folder where the app stores it's data. 

Perhaps as a standard this extra folder will be called 'data' by default but can be overriden by the call to InitialisePod().

Also, all of these are within a folder, like "podnotes". As the default the app name from pubspec.yaml is used, but allow a user to override.

**Comment by zheyxu** [comment]
Hi @gjwgit, the working branch is here https://github.com/anusii/keypod/tree/zy/2_initialise_pod. Please have a look.

**Comment by gjwgit** [comment]
Current status: GUI implemented but not yet the functionality.

**Comment by zheyxu** [comment]
@anushkavidanage 

Current progress is that
User log in but cannot save the note.

![Image](https://github.com/anusii/solid/assets/79696631/614ab2b2-a825-4da9-85d2-a329e608d5fd)

**Comment by anushkavidanage** [comment]
Tested. Creation of resources worked with some minor modifications. But after creating all the resources, the page does not redirect to anywhere. It keeps loading. Also currently there is only one file for the whole functionality which is 1085 lines long. Need to restructure that.

**Comment by anushkavidanage** [comment]
Changes made are in https://github.com/anusii/solid/tree/zy/2_initialise_pod

**Comment by gjwgit** [comment]
- [ ] Would the LOUTOUT be better as a NOT NOW. It will still logout but return to the app login screen if requiredLogin is true or the app main page if requireLogin is false.

- [ ] When I click LOGOUT it eventually takes me to the POD Note Taker page - why does it do that? There should be no PODNotes stuff here. It should go to the child passed through SolidLogin(child: XXX)?

- [ ] Yes, this file is too large and the widget hierarchy does not fit on a single page. It needs to be refactored.

- [ ] When I choose SUBMIT it seems to sit on this screen forever, even though I can see everything is created underneath? I tested this twice to see the same.
 
![image](https://github.com/anusii/solid/assets/1681429/095bb5eb-2f18-4b37-8873-0e666344c0c7)

Everything is created:

![image](https://github.com/anusii/solid/assets/1681429/9fcba52f-272a-4662-8a88-96ef4f54881a)

**Comment by gjwgit** [comment]
Ok, so re-engineering is a blocker. 

Can I please make use of this current implementation now so we can get some progress. 

It needs a merge from dev I think following the solidpod rename.
