### ISSUE TITLE
BUG: Cancelling from security key - goes to blank screen

### ISSUE THREAD

**Issue by zheyxu** [anusii/solidpod#228]
# Description
In MSFatigue app, if click `Cancel` button, the app goes to blank screen.

![Image](https://github.com/user-attachments/assets/34add17a-1330-4c7b-b2bc-66b78b323a91)

**Comment by zheyxu** [comment]
Made pr https://github.com/anusii/solidpod/pull/229

**Comment by srodriguez142857** [comment]
Anushka double-checked with Zheyuan.
The changed that Zheyuan did is not compatible with the other apps.
We are closing this issue.
