### ISSUE TITLE
SOLIDPOD: Implement SolidLoginPopup() for bstim

### ISSUE THREAD

**Issue by gjwgit** [anusii/solidpod#3]
# Description

Not all apps will need to immediately log into the POD on startup. An example is BSTIM which only needs PODs when a survey is to be submitted. This use case is for a solid pod login popup that will establish a connection to the pod. 

If a WebID is not known then prompt for it and save it locally, then connect to the server to retrieve the token.

The token should be retained so that no further login is required for reading/writing data during the app session.

If the app folder does not exist for the user on the solid server then run the InitialisePod() widget from #2 

# Closing Criteria

- [ ] This popup is deployed into bstim
- [ ] This popup is deployed into keypod on the LOAD button

**Comment by gjwgit** [comment]
Could this be assigned to Kevin? Start to have a look at how this will work. Thanks.

**Comment by junhaow1** [comment]
Assign myself to this ticket

**Comment by junhaow1** [comment]
https://github.com/anusii/solidpod/tree/kev/3_popup 
working branch

**Comment by junhaow1** [comment]
<img width="491" alt="image" src="https://github.com/anusii/solidpod/assets/37771259/597a7a2f-fdbe-4947-a2dd-1a950bc30a4f">

<img width="781" alt="image" src="https://github.com/anusii/solidpod/assets/37771259/a0cb3ea3-13d3-42c0-8a23-0beac54a0bc6">

**Comment by junhaow1** [comment]
{client: Instance of 'Client', rsaInfo: {rsa: Instance of 'KeyPair', privKeyJwk: {kty: RSA, d:
AsEnVm1Pl2haInojpsg0cHmKaHYw6Q8vOdm7dbdHzjd4ffPPQetyRAncx5MvH8BVsH7p1_y97dc7q-1gmFH4_3-7W8v3Zie7y_rhOW0JY2zxKY1pS7zh-dX1XDEIwmS-PegwPWP_9Mphj4t5b8P9iJU1LrZdCrES459dVOgBanVgx-6mV2tO2dIg-Q3WgQa-NUlUhV0yWwEdCRPwKS1BWkKieB8Le1T
8AcgaL7XvvrgHkUZMn_Ek_NoBbSH2z25eLg6hgmf0qJtGgdtcr0OkyvuV7xP9Z0gJl7wvAy3RVygtZTYTrvVYbhw2q_1cuWkgOIitFuvpIm8SNY9Ls-Km4Q, dp:
i8ywJHUp7ZmPiDl_8wdOgTUwbZTiQl6-ZwTFzLci_we58uRQXxBK62cKnBU07Xj2jH9eOUgW8TIDUFC3xDCUZFDBpeWBTWFfd-OumfzwrO7-D0iyJOnTJpyASTbqzVi3q9WmD4U0Wyfj-nukUXeYNTQrx3y09bOluf1Ndrtsx2c, dq:
KqKa6XpQY7-lgg4NOFT-X2XAQ1_EV9DYkFZK4yZ8lBVAxUxACIPJZH5V2UkoqMDG69H6N0C1wMWSNEG-ZlJxWxbMrtEDL1ORlQh9HoYDQNZcdz-Whh3AradXPU6rPjvLjYN9MBiuRnCOfyAhzCGQwJajKkr7Uh6X0Ii9B0js21E, e: AQAB, n:
rpYOwEjLMf9kOn9KAfHxUDYxBZha7LZKh-mL_rKiyNuIhcThO5gPt7zcNXgAugw9myK-3H4_B7cXEJmhWUUne3oF00Sg9WMFYDq6QevmXar6LjE7NYWfnu54XLGBGKKSPAV7r9e632cUx0_25hwNBCUUSC58DWXmbID6nsifEAxbYsf-Mcmc6cPMfQ2u0ZDE34qhkOwly7cygEsU0V00Huwml7qCbeU
DwOd-ZH4W_r_OeSXLTHcScN9rpdWSmMEcr5sJzLXlYtcjAIKIAu-X_JdCYJebbuAggItO_t1BdC5y3KryiczeAg7NC2oEPiG8TLCCcPyPpmTTWoAY8SbOMw, p:
0rkymfntC6Mqj_cZOJKMDXg_FmY_krn60Tc9PK4pkc5q-Zn1Vtg0Hi5fiCsa-fndbE6zsNVI28oF0bWi5ONk5Pm0o4OGa4pjaC5vU5N3Y2FBnEl3QdIWJyEByEi0MeEkQUr1Tv5eSnu_LSnxuPTCEePBced_R_isDde2Non5Yws, q:
1Bki8NPs109E3KnmtOsG4vh-GRtk2FevfvKniKKaf0cZgXotQMiT2IIp43RIA5p60r2K4vKImTDBRPu81_J4CwpfU7VDg5wO74XaIHlKot-S0n2k71Ug6BlHe_nK2dr1Qo5fwP-KdPWQTCXLThD2SXEhK2AkobaVdKSVFZuTunk, qi:
iSz5wgiGgZS6kxZNJwF-EkOxtxI-ePTOt-bytD2SRkfE5iBGN6SJnSUD1q6ym5VG9fKS3msnumj0IHFP-6YE0KbmWbjCB5Wyy0FOI2RNMUrEs-CzP2cq1HUvlYze7mB24IBkYtVS4WeBrJnK58BxG42SHcZSxVySb6h5pMCkwcc}, pubKeyJwk: {kty: RSA, e: AQAB, n:
rpYOwEjLMf9kOn9KAfHxUDYxBZha7LZKh-mL_rKiyNuIhcThO5gPt7zcNXgAugw9myK-3H4_B7cXEJmhWUUne3oF00Sg9WMFYDq6QevmXar6LjE7NYWfnu54XLGBGKKSPAV7r9e632cUx0_25hwNBCUUSC58DWXmbID6nsifEAxbYsf-Mcmc6cPMfQ2u0ZDE34qhkOwly7cygEsU0V00Huwml7qCbeU
DwOd-ZH4W_r_OeSXLTHcScN9rpdWSmMEcr5sJzLXlYtcjAIKIAu-X_JdCYJebbuAggItO_t1BdC5y3KryiczeAg7NC2oEPiG8TLCCcPyPpmTTWoAY8SbOMw, alg: RS256}}, authResponse: Instance of 'Credential', tokenResponse: {expires_at: 1709165571,
access_token:
eyJhbGciOiJFUzI1NiIsInR5cCI6ImF0K2p3dCIsImtpZCI6InU1elVKaE9LNmFTaElXS0l5b2VjeXJSekNXaUdtS0l6WWNRNFBzdVV4d2sifQ.eyJ3ZWJpZCI6Imh0dHBzOi8vcG9kcy5zb2xpZGNvbW11bml0eS5hdS9rZXZpbi9wcm9maWxlL2NhcmQjbWUiLCJqdGkiOiJUdzBtNllFbGtYXzNy
N3NWQURHNFgiLCJzdWIiOiJodHRwczovL3BvZHMuc29saWRjb21tdW5pdHkuYXUva2V2aW4vcHJvZmlsZS9jYXJkI21lIiwiaWF0IjoxNzA5MTYxOTcwLCJleHAiOjE3MDkxNjU1NzAsInNjb3BlIjoiIiwiY2xpZW50X2lkIjoidnhjMllxSm5mSllPQ0o2WWNIQ1VPIiwiaXNzIjoiaHR0cHM6Ly9
wb2RzLnNvbGlkY29tbXVuaXR5LmF1LyIsImF1ZCI6InNvbGlkIiwiY25mIjp7ImprdCI6IjY2eDdhUUYzYjZCMEc1WFBiSjktM0o1VjBUOURWa2hmeGFqNmJwT0VRM3MifX0.8ONrJ1-OapStxUmBG2Ci8mKIL0sG5atGUQbYrvJ3qPe4-3YAZfLzmbrxuF_HSH8MO7nGyafFez-av-txI9xY0g,
expires_in: 3600, id_token:
eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InU1elVKaE9LNmFTaElXS0l5b2VjeXJSekNXaUdtS0l6WWNRNFBzdVV4d2sifQ.eyJhenAiOiJ2eGMyWXFKbmZKWU9DSjZZY0hDVU8iLCJzdWIiOiJodHRwczovL3BvZHMuc29saWRjb21tdW5pdHkuYXUva2V2aW4vcHJvZmlsZS9jYXJk
I21lIiwiYXRfaGFzaCI6InlhVS1ydDk2ZmRjdTIwVGJwdEdlTnciLCJhdWQiOiJ2eGMyWXFKbmZKWU9DSjZZY0hDVU8iLCJleHAiOjE3MDkxNjU1NzAsImlhdCI6MTcwOTE2MTk3MCwiaXNzIjoiaHR0cHM6Ly9wb2RzLnNvbGlkY29tbXVuaXR5LmF1LyJ9.EbGhGSW5F-Qndj7H5yGIkKEXtaruCk
6CSW7XkfX4dGfabYNcdN2gpvgTm9gkhY6TPoXrqqOlAnTii_G5LMuoVg, scope: , token_type: DPoP}, accessToken:
eyJhbGciOiJFUzI1NiIsInR5cCI6ImF0K2p3dCIsImtpZCI6InU1elVKaE9LNmFTaElXS0l5b2VjeXJSekNXaUdtS0l6WWNRNFBzdVV4d2sifQ.eyJ3ZWJpZCI6Imh0dHBzOi8vcG9kcy5zb2xpZGNvbW11bml0eS5hdS9rZXZpbi9wcm9maWxlL2NhcmQjbWUiLCJqdGkiOiJUdzBtNllFbGtYXzNy
N3NWQURHNFgiLCJzdWIiOiJodHRwczovL3BvZHMuc29saWRjb21tdW5pdHkuYXUva2V2aW4vcHJvZmlsZS9jYXJkI21lIiwiaWF0IjoxNzA5MTYxOTcwLCJleHAiOjE3MDkxNjU1NzAsInNjb3BlIjoiIiwiY2xpZW50X2lkIjoidnhjMllxSm5mSllPQ0o2WWNIQ1VPIiwiaXNzIjoiaHR0cHM6Ly9
wb2RzLnNvbGlkY29tbXVuaXR5LmF1LyIsImF1ZCI6InNvbGlkIiwiY25mIjp7ImprdCI6IjY2eDdhUUYzYjZCMEc1WFBiSjktM0o1VjBUOURWa2hmeGFqNmJwT0VRM3MifX0.8ONrJ1-OapStxUmBG2Ci8mKIL0sG5atGUQbYrvJ3qPe4-3YAZfLzmbrxuF_HSH8MO7nGyafFez-av-txI9xY0g,
idToken: Instance of 'IdToken', refreshToken: null, expiresIn: 0:59:59.956000, logoutUrl:
https://pods.solidcommunity.au/.oidc/session/end?id_token_hint=eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InU1elVKaE9LNmFTaElXS0l5b2VjeXJSekNXaUdtS0l6WWNRNFBzdVV4d2sifQ.eyJhenAiOiJ2eGMyWXFKbmZKWU9DSjZZY0hDVU8iLCJzdWIiOiJod
HRwczovL3BvZHMuc29saWRjb21tdW5pdHkuYXUva2V2aW4vcHJvZmlsZS9jYXJkI21lIiwiYXRfaGFzaCI6InlhVS1ydDk2ZmRjdTIwVGJwdEdlTnciLCJhdWQiOiJ2eGMyWXFKbmZKWU9DSjZZY0hDVU8iLCJleHAiOjE3MDkxNjU1NzAsImlhdCI6MTcwOTE2MTk3MCwiaXNzIjoiaHR0cHM6Ly9w
b2RzLnNvbGlkY29tbXVuaXR5LmF1LyJ9.EbGhGSW5F-Qndj7H5yGIkKEXtaruCk6CSW7XkfX4dGfabYNcdN2gpvgTm9gkhY6TPoXrqqOlAnTii_G5LMuoVg}

**Comment by junhaow1** [comment]
in progress, working on saving auth data/token for use on other pages as in SolidLogin()

**Comment by junhaow1** [comment]
found difficulty converting authdata (Map format) into String using serializeMap so that we can save them in secureStorage. Dawei suggested I can convert the map into Json format first, then save as a string using secureStorage.

**Comment by cdawei** [comment]
This page might be useful for converting the `authData` between a `String` and a `Map` https://docs.flutter.dev/data-and-backend/serialization/json

**Comment by junhaow1** [comment]
/// Store authentication data
  authData = {
    'client': client,
    'rsaInfo': rsaResults,
    'authResponse': authResponse,
    'tokenResponse': tokenResponse,
    'accessToken': accessToken,
    'idToken': tokenResponse.idToken,
    'refreshToken': tokenResponse.refreshToken,
    'expiresIn': tokenResponse.expiresIn,
    'logoutUrl': _logoutUrl
  }; 

how to Serialize JSON for each map value . 

error I got: Converting object to an encodable object failed: Instance of 'Client’

**Comment by cdawei** [comment]
So Anushka mentioned that re-creating the `client` instance can be done through:
```code
var client = Client(issuer, _clientId, clientSecret: _clientSecret);
```
where both the `_clientId` and `_clientSecret` are strings (so can be serialised).
The `issuer` variable can be recreated through:
```code
Issuer issuer = await Issuer.discover(issuerUri);
```
where `issuerUri` is the same as the one when calling the `authenticate` function.

Therefore, it seems that we should be able to recreate the `client` instance by saving the `_clientId`, `_clientSecret` and `issuerUri`.

**Comment by junhaow1** [comment]
> So Anushka mentioned that re-creating the `client` instance can be done through:
> 
> ```
> var client = Client(issuer, _clientId, clientSecret: _clientSecret);
> ```
> 
> where both the `_clientId` and `_clientSecret` are strings (so can be serialised). The `issuer` variable can be recreated through:
> 
> ```
> Issuer issuer = await Issuer.discover(issuerUri);
> ```
> 
> where `issuerUri` is the same as the one when calling the `authenticate` function.
> 
> Therefore, it seems that we should be able to recreate the `client` instance by saving the `_clientId`, `_clientSecret` and `issuerUri`.

Thanks @cdawei  on it

**Comment by junhaow1** [comment]
demo video: 

<img width="416" alt="image" src="https://github.com/anusii/solidpod/assets/37771259/379cdea3-6731-48ca-8004-1ade448f853a">

https://github.com/anusii/solidpod/assets/37771259/4244aefc-7520-4f43-b1de-4a76146ae9ba

**Comment by junhaow1** [comment]
// Get the authentication data from the secure storage.

                                          const storage =
                                              FlutterSecureStorage();
                                          String? jsonAuthData = await storage
                                              .read(key: 'authData');
                                          Map<String, dynamic> deserializedMap =
                                              json.decode(jsonAuthData!);
                                          var rsaInfo =
                                              deserializedMap['rsaInfo'];
                                          KeyPair deserializedKeyPair = KeyPair(
                                            rsaInfo['rsa']['publicKey'],
                                            rsaInfo['rsa']['privateKey'],
                                          );
                                          var pubKeyJwk = rsaInfo['pubKeyJwk'];
                                          Map<String, dynamic> authData = {
                                            'accessToken':
                                                deserializedMap['accessToken'],
                                            'rsaInfo': {
                                              'rsa': deserializedKeyPair,
                                              'pubKeyJwk': pubKeyJwk,
                                            },
                                          };

**Comment by junhaow1** [comment]
https://github.com/anusii/bstim/pull/364 

https://github.com/anusii/solidpod/pull/57

PR created

**Comment by gjwgit** [comment]
Let's review this today - that it is fully functional.
