### ISSUE TITLE
SOLID: use dart code linter as replacement of dart-code-metrics

### ISSUE THREAD

**Issue by zheyxu** [anusii/solidpod#46]
## Description
solid_lints package but it needs analyze 6.2.0 and dart_code_metrics does not work with analyze >6.0.0. Could you have a look to see if there is a chance to update our anusii/dart-code-metrics to work with analyze 6.2.0?

**Comment by zheyxu** [comment]
Use **analyzer 6.2.0** as current flutter sdk does not support analyzer **6.4.0**
Because every version of flutter from sdk depends on meta 1.10.0 and analyzer >=6.3.0 depends on meta ^1.11.0, flutter from sdk is incompatible with analyzer >=6.3.0.
And because every version of dart_code_metrics from git depends on analyzer ^6.4.0, flutter from sdk is incompatible with dart_code_metrics from git.

**Comment by gjwgit** [comment]
Should we try modifying the package to make it work with newer analyze? Or else move on from dart code metrics. Or else purchase a license for the new version.

**Comment by zheyxu** [comment]
The branch tries to work with newer analyzer https://github.com/anusii/dart-code-metrics/tree/zy/46_update_analyze

After solving the issues raised by `@Deprecated`, 

the commends like dart run **_dart_code_metrics:metrics check-unused-code --disable-sunset-warning lib_** cannot work properly.

**Comment by gjwgit** [comment]
Thanks for the pointer to dart code linter. It is a fork of dart code metrics. Let's move to using that. 

I have edited the title to reflect this.

**Comment by zheyxu** [comment]
Using dart-code-linter raises the issue of 
`Because every version of solidpod from path depends on http ^1.1.2 and every version of dart_code_linter depends on http ^0.13.5, solidpod from path is incompatible with dart_code_linter.
So, because keypod depends on both dart_code_linter ^1.1.1 and solidpod from path, version solving failed.`

And dart-code-linter has the issue of analyzer 6.0 error. Currently it is not smooth to use dart-code-linter.
