### ISSUE TITLE
APPS: Explore how to use refresh token

### ISSUE THREAD

**Issue by anushkavidanage** [anusii/solidpod#58]
# Description
Currently, when the login token expires we direct user to the login page again for the login. Instead, we have a refresh token that we might be able to use to keep the user logged in.

# Why
Improves user friendliness

# Closing Criteria
- [ ] Use refresh token to keep the user logged in

**Comment by anushkavidanage** [comment]
Currently, our Solid servers do not return with a refresh token. This might have to do something with the server configuration. 

Needs further research.

**Comment by anushkavidanage** [comment]
Solid discussion forum post: https://forum.solidproject.org/t/getting-a-refresh-token-from-css/7310/5

According to the response I received, this might be related to the server configuration side rather than OIDC flow of authentication. This needs further exploration.

**Comment by gjwgit** [comment]
Dawei notes Anushka found there is a Simple solution to getting the REFRESH token.

This task is to now use that to refresh the auth.
