### ISSUE TITLE
SOLIDPOD: Rename solid.dart to solidpod.dart

### ISSUE THREAD

**Issue by cdawei** [anusii/solidpod#60]
Rename the `lib/solid.dart` to `lib/solidpod.dart` to follow the convention used in [solid-auth](https://github.com/anusii/solid-auth) and [solid-encrypt](https://github.com/anusii/solid-encrypt).

- [x] Rename `lib/solid.dart` in `solidpod`
- [ ] Rename the import of `solid.dart` in `keypod`

**Comment by gjwgit** [comment]
I merged the PR and closed.
