### ISSUE TITLE
INITIALIZE POD: Alert layout improvements

### ISSUE THREAD

**Issue by gjwgit** [anusii/solidpod#62]
## Description

The Alert box in the InitialisePods() could be better laid out and support a scrolling widget.

In the below screenshot, there is a lot of empty space on the left inside the Alert box that does not need to be there.

On my Linux desktop and Android version I can't seem to scroll the Alert box to see the full message. 

![Image](https://github.com/anusii/solidpod/assets/1681429/0796c72b-020a-4a8f-8eb5-69b035fb0408)

**Comment by junhaow1** [comment]
<img width="500" alt="image" src="https://github.com/anusii/solidpod/assets/37771259/75145f01-0137-48af-a9fa-4f92d4cf73b7">
make the text scrollable, font size smaller, left and right padding smaller , title in the center

**Comment by junhaow1** [comment]
https://github.com/anusii/solidpod/pull/84 PR created

**Comment by junhaow1** [comment]
merged , can be closed
