### ISSUE TITLE
INITIALISE POD: Request Password Key first

### ISSUE THREAD

**Issue by gjwgit** [anusii/solidpod#63]
## Description

In the current InitialisePod page the Password is asked for right at the bottom of the page. Most the the list of resources is probably not very interesting to the user. But the Password is critical.

Perhaps ask for the password first and then the check box then the SUBMIT/RESET buttons then the list of resources that will be created.

**Comment by junhaow1** [comment]
fixed in https://github.com/anusii/solidpod/issues/65

**Comment by gjwgit** [comment]
Looks good and ready to merge once @cdawei's suggestion ipmlemented - see PR.
