### ISSUE TITLE
INITIALISE POD: On Android and narrow screen the SUBMIT/RESET buttons are rendered poorly

### ISSUE THREAD

**Issue by gjwgit** [anusii/solidpod#64]
## Description

Linux Desktop

![Image](https://github.com/anusii/solidpod/assets/1681429/2a7dc66c-4772-4391-b1cc-49f35f51895e)

On Pixel 7a

![Image](https://github.com/anusii/solidpod/assets/1681429/c722af6a-e66c-4028-9b67-04e675f8f5a7)

**Comment by junhaow1** [comment]
https://github.com/anusii/solidpod/pull/85 PR created

**Comment by junhaow1** [comment]
![Image](https://github.com/anusii/solidpod/assets/37771259/c4dc02ae-58cc-486a-9c1e-df6e23857cce)

**Comment by gjwgit** [comment]
I still get messed buttons. Perhaps they need to be aligned one per line for small screen?

**Comment by anushkavidanage** [comment]
Remove `Reset` button

**Comment by zheyxu** [comment]
Easy solution:
padding: const EdgeInsets.symmetric(horizontal: 0),

**Comment by gjwgit** [comment]
Thanks for that @zheyxu. Let's also now remove the RESET button as not required.

**Comment by junhaow1** [comment]
<img width="745" alt="image" src="https://github.com/anusii/solidpod/assets/37771259/c03a0772-0cf8-419a-8b50-3b1c6268b49a">

removed the "reset" button
