### ISSUE TITLE
INITIALIZE POD: Remove the popup warning for checkbutton and reconstruct the whole page

### ISSUE THREAD

**Issue by gjwgit** [anusii/solidpod#65]
## Description

Currently the popup warning when the checkbutton is not ticked is very generic, talking about an invalid form. 

Please be very specific about what the user needs to do next: *Please confirm that you are aware that we will create resources on your Solid Pod to continue. Please tap the checkbox.*

![Image](https://github.com/anusii/solidpod/assets/1681429/91db69b6-1c6c-4d12-93a6-5661c810b296)

**Comment by anushkavidanage** [comment]
Try removing the popup error dialog

**Comment by gjwgit** [comment]
Remove the popup and rely on the package being used that highlights in red messages indicating issues.

**Comment by junhaow1** [comment]
![Image](https://github.com/anusii/solidpod/assets/37771259/d9868490-ef04-4484-a533-d9f33d7bbebe)

**Comment by junhaow1** [comment]
- [ ] removed the popup warning for checkbutton 
- [ ] request password key first, then submit button, then resources created 
- [ ] Password entry will not be lost if the checkbox is not selected

**Comment by gjwgit** [comment]
Tested on Linux. Works great. once the Rsource list is cleaned up then this will be closed with the PR.

**Comment by junhaow1** [comment]
<img width="864" alt="image" src="https://github.com/anusii/solidpod/assets/37771259/f0252905-d4a5-43b0-b886-783714aca692">

**Comment by gjwgit** [comment]
Please sort the file/folder list

**Comment by gjwgit** [comment]
How did this go?

If it is difficult then let's merge current and do in another task. It would be good to get this into dev. Thanks.

**Comment by junhaow1** [comment]
sorted resource list:

![Image](https://github.com/anusii/solidpod/assets/37771259/945f2d17-b9fc-4c91-b2d8-8c31cce4ec88)

**Comment by junhaow1** [comment]
merged, can be closed
