### ISSUE TITLE
INITIALISE POD: After the Warning popup I have lost my password entry

### ISSUE THREAD

**Issue by gjwgit** [anusii/solidpod#66]
## Description

Use case: I have entered the PASSWORD, very carefully, and then very carefully entered the RETYPE PASSWORD but I forget to tick the Checkbox. A warning pops up and it has wiped my `PASSWORDS!` Arghhh. Now I have to start again - It should not wipe my password.

**Comment by junhaow1** [comment]
fixed in https://github.com/anusii/solidpod/issues/65

**Comment by gjwgit** [comment]
Confirm this is no longer an issue.

Once the resource list is cleaned up this can be closed wit the merge of the combined PR.

**Comment by junhaow1** [comment]
can be clsoed
