### ISSUE TITLE
SOLIDPOD: Enhance SolidLoginPopup Widget with Conditional Authentication Flow Logic

### ISSUE THREAD

**Issue by junhaow1** [anusii/solidpod#80]
## Description

Integrate a conditional authentication logic into the SolidLoginPopup widget to streamline the login process. The enhancement involves an automated attempt to retrieve authData from secure storage initially. If this retrieval is successful, the widget will maintain the current state without further action. However, if the retrieval fails, the widget should trigger the popup login window, allowing users to proceed with the standard authentication procedure already in place.

1. try to retrieve the `authData` from secure storage
2. if step 1 is successful, do nothing
3. otherwise, show the popup login window and do the normal authentication

## Why

Implementing this logic enhances the user experience by making the authentication process seamless and efficient. It minimizes unnecessary interactions, ensuring that users who have previously authenticated and have their authData stored can bypass the login popup, thus offering a smoother user journey. This update is crucial for maintaining a user-friendly, secure, and efficient authentication flow, especially in applications where frequent re-authentication can be a hindrance to user engagement.
## Closing Criteria

 

- [ ] The widget successfully retrieves authData from secure storage when available.

- [ ] No further action is taken if authData is successfully retrieved, maintaining the current user session.
 - [ ] The login popup window is triggered automatically if authData is not found, allowing the user to authenticate.
 - [ ] Ensure the normal authentication process remains intact and is triggered appropriately when needed.

**Comment by cdawei** [comment]
Close as no longer relevant.
