### ISSUE TITLE
SOLID LOGIN: Extra parameters to support

### ISSUE THREAD

**Issue by gjwgit** [anusii/solidpod#81]
## Description

Probably a good idea to collect additional tuning parameters for SolidLogin and implement as time permits.

- [ ] continueFG: The choice for foreground colour of the continue button
- [ ] loginBG and loginFG
- [ ] registerBG and registerFG
- [ ] infoBG and infoFG

**Comment by gjwgit** [comment]
Note that the KeyPod app demonstrates how the implementation of continueBG is not working. We are not picking up the default (modified in KeyPod) button background. It is white and should not be.

This needs to be resolved before we implement the remaining paramets.

**Comment by gjwgit** [comment]
Current status?

- [ ] Is there a better approach to handling a group of parameter values like this. Each of the 4 buttons have the same set of parameters/style. Perhaps we have a PodButtonStyle that consists of the defaults for text:, background:, foreground:, tooltip:, displayed:, and maybe some others later on. Id this how things are done in Flutter? Then

```
SolidLogin(
    ...
    continueButton: const PodButtonStyle(
        text: 'CONTINUE', 
        background: Colors.white, 
        tooltip: 'Continue to the app without logging in to your Solid Pod'
    ),
    ...
)
```

**Comment by junhaow1** [comment]
![Image](https://github.com/anusii/solidpod/assets/37771259/da38f050-69ff-4c89-a178-56af5d8fb8bc)

**Comment by junhaow1** [comment]
https://github.com/anusii/solidpod/pull/97 PR created

**Comment by gjwgit** [comment]
Requested this be a data class not a widget exposed externally.

**Comment by junhaow1** [comment]
https://github.com/anusii/solidpod/assets/37771259/69e5cb83-67eb-400b-96ef-20829ed04f56

**Comment by junhaow1** [comment]
home: const SolidLogin(
        // Images generated using Bing Image Creator from Designer, powered by
        // DALL-E3.

        title: 'MANAGE YOUR SOLID KEY POD',
        image: AssetImage('assets/images/keypod_image.jpg'),
        logo: AssetImage('assets/images/keypod_logo.png'),
        link: 'https://github.com/anusii/keypod',
        required: false,
        continueButtonStyle: PodButtonStyle(
          text: 'CONTINUE',
          background: Colors.lightBlue,
          foreground: Colors.black,
          tooltip: 'Test the app without logging in.',
        ),
        child: Home(
          appName: 'KeyPod',
        ),
      ),

**Comment by junhaow1** [comment]
merged, can be closed
