### ISSUE TITLE
Why are there hard coded references to keypod in solidpod?

### ISSUE THREAD

**Issue by gjwgit** [anusii/solidpod#92]
## Description

Not sure why these appear in solidpod?

```
02 Apr 21:16:57 gjw@kadesh ~keypod/solidpod$ rgrep keypod lib
lib/src/solid/api/rest_api.dart:  final keyFileUrl = webId!.replaceAll(profCard, 'keypod/$encDir/$encKeyFile');
lib/src/screens/initial_setup/initial_setup_screen_body.dart:                          image: AssetImage('assets/images/keypod_image.jpg'),
lib/src/screens/initial_setup/initial_setup_screen_body.dart:                          logo: AssetImage('assets/images/keypod_logo.png'),
lib/src/screens/initial_setup/initial_setup_screen_body.dart:                          link: 'https://github.com/anusii/keypod',
```

**Comment by junhaow1** [comment]
https://github.com/anusii/solidpod/pull/101 PR created 

- [ ] make prep

**Comment by junhaow1** [comment]
That works well with the submit button now the focus.

We need to capture the "Why" in the working or a tooltip for the Logout button - why would I be interested to logout at this time? Presumably to then login as another user (who may already have data). If that's the case then lets explain that.

**Comment by junhaow1** [comment]
PR merged, can be closed
