### ISSUE TITLE
Add tooltips to the 4 login buttons

### ISSUE THREAD

**Issue by gjwgit** [anusii/solidpod#94]
## Description

For the 4 login buttons (LOGIN, CONTINUE, GET A POD, INFO) add tooltips with default text that are overridden by an app calling SolidLogin() with loginTooltip, continueTooltip, registerTooltip, and infoTooltip. Default text:

![Image](https://github.com/anusii/solidpod/assets/1681429/aaed0a2c-62fc-4746-a797-68f4499c0296)

## Why

To explain to the user the purpose of each button before they tap the button.

## Closing Criteria

- [ ] Tooltips work on desktop
- [ ] Tooltips work on web
- [ ] Tooltips wok on mobile

**Comment by junhaow1** [comment]
fixed in https://github.com/anusii/solidpod/issues/81

**Comment by junhaow1** [comment]
merged, can be closed
